name: "Convert md to ADF"
on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  test-local:
  # run with "act" in repo directory
    name: converting md-to-adf
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Notes with curl
        id: note
        run: |
          release_info=$(curl --request GET \
            --url https://api.github.com/repos/Akhil16/action-md-to-adf/releases/tags/v1.0.0 \
            --header 'authorization: Bearer <redacted>' \
            --header 'Accept: application/vnd.github+json' \
            --header 'X-GitHub-Api-Version: 2022-11-28')
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "NOTES<<$EOF" >> "$GITHUB_OUTPUT"
          echo  "$release_info" | jq -r '.body' >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"
       # Clone this repo
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./
        id: convert
        with:
          md-text: ${{steps.note.outputs.NOTES}}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Comment on Jira ticket
        run: node jira_comment.js
        env:
          JIRA_API_TOKEN: <redacted>
          JIRA_TICKET_ID: <ticketid>
          COMMENT_DATA:  ${{steps.convert.outputs.adf-output}}
